channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.0.2
- pip:
  - mlflow==2.16.0
  - pandas==2.2.2
  - matplotlib==3.9.2
  - pickle4==0.0.1
  - seaborn==0.13.2
  - bokeh==3.4.0
name: mlflow-env
